---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes
      chart: pihole
      version: 2.27.0
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    replicaCount: 1

    image:
      repository: 'pihole/pihole'
      tag: '2024.07.0'

    dualStack:
      enabled: true

    serviceDns:
      type: LoadBalancer
      port: 53
      annotations:
        lbipam.cilium.io/ips: '192.168.20.3,192.168.20.4'
    serviceDhcp:
      enabled: false
    ingress:
      enabled: true
      ingressClassName: internal
      hosts:
        - pihole.${SECRET_DOMAIN}
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
    persistentVolumeClaim:
      enabled: false
    admin:
      existingSecret: 'pihole-secret'
      passwordKey: 'password'
    extraEnvVars:
      DNSMASQ_LISTENING: all
      DNSSEC: 'false'
      WEBUIBOXEDLAYOUT: traditional
      WEBTHEME: default-auto

    DNS1: '1.1.1.1' #'192.168.20.3#5053'
    DNS2: '1.0.0.1' #'192.168.20.4#5053'
    doh:
      enabled: false

    dnsmasq:
      additionalHostEntries: []

      customSettings:
        - no-resolv
        - no-poll

    adlists: []

    extraVolumes:
      startup:
        configMap:
          name: pihole-startupscript

    extraInitContainers:
      - name: update-lists
        image: pihole/pihole
        tag: '2024.07.0'
        command:
          - 'sh'
        args:
          - '-c'
          - >
            cp /config/update.sh /config/run.sh
            && chmod 700 /config/run.sh
            && /config/run.sh
        volumeMounts:
          - name: startup
            mountPath: /config/update.sh
            subPath: update.sh
          - name: config
            mountPath: /etc/pihole

    monitoring:
      podMonitor:
        enabled: true
      sidecar:
        enabled: true
        image:
          repository: ekofr/pihole-exporter
          tag: v0.4.0
          port: 9617
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi
    podDnsConfig:
      enabled: true
      policy: 'None'
      nameservers:
        - 127.0.0.1
        - 1.1.1.1
        - 1.0.0.1
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    virtualHost: 'pihole.${SECRET_DOMAIN}'
  valuesFrom:
    - kind: ConfigMap
      name: pihole-devices-helm-values
