---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
# this secret gets manually created at bootstrap, and then this takes control of it
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bitwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: bitwarden
    template:
      data:
        # this can NOT end in a newline or it doesn't work
        token: '{{ .key }}'
  data:
    - secretKey: key
      remoteRef:
        key: bitwarden-machine-key
