---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: cross-seed-secret
    template:
      data:
        config.js: |
          module.exports = {
            action: "inject",
            apiKey: "{{.CROSS_SEED_API_KEY}}",
            delay: 30,
            duplicateCategories: true,
            flatLinking: false,
            includeEpisodes: true,
            includeNonVideos: true,
            includeSingleEpisodes: true,
            seasonFromEpisodes: 1.0,
            linkCategory: "cross-seed",
            linkDirs: [
              "/media/downloads/qbittorrent/complete/cross-seed"
            ],
            linkType: "hardlink",
            matchMode: "safe",
            outputDir: "/config",
            port: Number(process.env.CROSS_SEED_PORT),
            qbittorrentUrl: "http://{{ .QBITTORRENT_USER }}:{{ .QBITTORRENT_PASS }}@qbittorrent.downloads.svc.cluster.local",
            radarr: [
              "http://radarr.downloads.svc.cluster.local/?apikey={{ .RADARR_API_KEY }}"
            ],
            skipRecheck: true,
            sonarr: [
              "http://sonarr.downloads.svc.cluster.local/?apikey={{ .SONARR_API_KEY }}"
            ],
            torznab: [
              1,
              3,
              10,
              11,
              12,
            ].map(i => `http://prowlarr.downloads.svc.cluster.local/$${i}/api?apikey={{ .PROWLARR_API_KEY }}`),
            useClientTorrents: true
          };
  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: prowlarr
    - extract:
        key: qbtools
