image:
  repository: quay.io/mittwald/kubernetes-replicator
  tag: v2.11.0
grantClusterAdmin: false
args:
  - -resync-period=5m
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
