---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: esphome-secrets
    creationPolicy: Owner
    template:
      data:
        secrets.yaml: |-
          wifi_ssid: "{{ .ESPHOME_WIFI_SSID }}"
          wifi_pwd: "{{ .ESPHOME_WIFI_PASSWORD }}"
          wifi_fallback_ssid_password: "{{ .ESPHOME_WIFI_FALLBACK_SSID_PASSWORD }}"

          mqtt_host: mqtt.${SECRET_DOMAIN}
          mqtt_user: "{{ .X_EMQX_MQTT_USERNAME }}"
          mqtt_pwd: "{{ .X_EMQX_MQTT_PASSWORD }}"

          domain_devices: iot.internal
  dataFrom:
    - extract:
        key: esphome
    - extract:
        key: emqx
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-deploykey
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: esphome-deploykey
    creationPolicy: Owner
  data:
    - secretKey: id_ed25519
      remoteRef:
        key: esphome
        property: github_deploy_key
