---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbtools
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: qbtools-secret
    template:
      data:
        QBITTORRENT_USER: '{{ .QBITTORRENT_USER }}'
        QBITTORRENT_PASS: '{{ .QBITTORRENT_PASS }}'
  dataFrom:
    - extract:
        key: qbtools
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbtools-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: qbtools-config-secret
    template:
      data:
        config.yaml: |
          {{ .config | toString }}
  data:
    - secretKey: config
      remoteRef:
        key: qbtools-config
