---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: qbittorrent-secret
    template:
      data:
        CROSS_SEED_API_KEY: '{{ .CROSS_SEED_API_KEY }}'
        PUSHOVER_TOKEN: '{{ .QBITTORRENT_PUSHOVER_TOKEN }}'
        PUSHOVER_USER_KEY: '{{ .PUSHOVER_USER_KEY }}'
        GLUETUN_CONTROL_SERVER_API_KEY: '{{ .GLUETUN_API_KEY }}'
  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: pushover
    - extract:
        key: qbittorrent
    - extract:
        key: gluetun
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wireguard-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: wireguard-secret
    template:
      engineVersion: v2
      data:
        VPN_SERVICE_PROVIDER: '{{ .VPN_SERVICE_PROVIDER }}'
        HEALTH_TARGET_ADDRESS: '{{ .HEALTH_TARGET_ADDRESS }}'
        WIREGUARD_PRIVATE_KEY: '{{ .WIREGUARD_PRIVATE_KEY }}'
        WIREGUARD_ADDRESSES: '{{ .WIREGUARD_ADDRESSES }}'
        SERVER_COUNTRIES: '{{ .SERVER_COUNTRIES }}'
        SERVER_CITIES: '{{ .SERVER_CITIES }}'
        VPN_PORT_FORWARDING_PROVIDER: '{{ .VPN_SERVICE_PROVIDER }}'
        UPDATER_VPN_SERVICE_PROVIDERS: '{{ .VPN_SERVICE_PROVIDER }}'
        GLUETUN_CONTROL_SERVER_API_KEY: '{{ .GLUETUN_API_KEY }}'
  dataFrom:
    - extract:
        key: gluetun
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent-gluetun
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: qbittorrent-gluetun-secret
    creationPolicy: Owner
    template:
      data:
        auth.toml: |
          [[roles]]
          name = "gluetun-qb-port-sync"
          routes = [
            "GET /v1/publicip/ip",
            "GET /v1/openvpn/portforwarded"
          ]
          auth = "apikey"
          apikey = "{{ .GLUETUN_API_KEY }}"
  dataFrom:
    - extract:
        key: gluetun
