# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:nlQsLdND95rO9hWe7L9bAQ55Ck2/tXkinWNm9y6zzs4=,iv:epEn7KP9CHSYDpSSmuTbu0VoVhRbk6r99WVZgvrkDig=,tag:oJCWNgPfNbmFepN6rZYOpQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1j34t6fwv5evlf9gxchc3x9v6zypufszzuynxycrxk4r4jwxtfq9ss9dmtr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aW9vMG5IemlqVHk3KzFa
        V1lWM0ltQkN3aVloZ3pBYnBZaXd3WWppZFZ3Ci9XaVlqS29rTVZXMFpMaTVuRllr
        YTloWTdlWHlQU3NJN2tFWTJVeUYrcm8KLS0tIGRZU3VNbVBmenUzSGJjdmQxS0o4
        YllyMGp0a3ZBdTFkMGViWmhLTU01NjAKMokFbM83A4eTFe/leGaUG0yf1tBllpjC
        M434fFpzNQKU0i3bAzBiHeUrDARN/5a9Vb74Xf4nUbHaNky8tKJc9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T02:00:04Z"
  mac: ENC[AES256_GCM,data:YrDJCNahjb7I4wbfN/5pviMolyoHJ6da5mKvXE/5jGHQOmWF0JfQdSKrqlRn3uzrb9OouydOXU+/qxLMsKQc6vob9a1dScK+TRzWjdzPxMLBm31HJzbErmmbycUl7ImHqIfWZpLVU1OOVLMgejW5aYIfSfmEurcSh84MSB/c3CE=,iv:mpENPDZqkvoNag1UhpEbw5SYrIqFMmN7Ffa3IGRehLk=,tag:OYRYm0AlgcFHAY8A9NEA0Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
