---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
# this secret gets manually created at bootstrap, and then this takes control of it
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-secrets
  annotations:
    replicator.v1.mittwald.de/replicate-to: '.*'
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: cluster-secrets
  dataFrom:
    - extract:
        key: cluster-secrets
