# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:UkrCSdoqmK52EfwoIgyivII1DEbflF06ucHk9Mc825j/pymFQpZgvQ==,iv:Ru9eW/xAOc3+TRmIIjofWkAPno/4s0OAVwnddhZmxvM=,tag:UZmmkozKRcBzDrb7X/Jzpw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1j34t6fwv5evlf9gxchc3x9v6zypufszzuynxycrxk4r4jwxtfq9ss9dmtr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMVo1R1MvaVlTWEh2djV3
        K01EbC9TTVFmbXJKdmVES3VqMktsTEo0M2tRCnNBaFBGSWM3c0tsOEpacTFQOERp
        TGl1S2hyNFgyaEpDRlNKRUJFWWgyNkkKLS0tIGFzYW4zWXBsaHF0OEwxbUo1c3Bi
        VVdqenkrUWFLM3NuNkphUncrV2w1TmsKru1EYzV616HpdJBTJ0NPsmuVKi3HtQMP
        NDzKr5thJyaWoR370XBEfAqDG+xotkvy6LTuy5cc2QG99hMvtKMwFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T02:00:04Z"
  mac: ENC[AES256_GCM,data:5E8Sdi2FYWkrE+sCULzohbY5UWbXiCh3+Mjf/nN2ti47aCZ02+7CzTyiLrv7+5lpE720s+ChoeZ2Uz0AXyPMCuZkuchJR/GEbbn0OZC5O4cc5swoIcyuIj7Bqu5cQP9rOqFlp+CULChU2fq3+PGy/rAloSiErojZdntg9HSjnzI=,iv:rqJG589Mvzd4n12t33KDQtRMbmI1GebdyHd5xx5rux8=,tag:vW0YTWhZ1Q8+V/jtoRh6qg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
