---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
# from https://github.com/auricom/home-ops/blob/main/kubernetes/apps/default/hajimari/app/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app hajimari
spec:
  interval: 1h
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    hajimari:
      title: Apps
      lightTheme: blackboard
      darkTheme: blackboard
      alwaysTargetBlank: true
      showSearch: false
      showGreeting: false
      showAppGroups: true
      showAppStatus: false
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: true
      namespaceSelector:
        any: true
      customApps:
        - group: servers
          apps:
            - name: nfs
              icon: mdi:nas
              url: 'https://nfs.servers.internal'
      globalBookmarks:
        - group: Kubernetes
          bookmarks:
            - name: tholinka/homelab
              icon: 'mdi:github'
              url: https://github.com/tholinka/homelab
              targetBlank: false
            - name: kubesearch
              icon: 'mdi:kubernetes'
              url: https://kubesearch.dev/
              targetBlank: false
    route:
      main:
        hostnames:
          - tholinka.dev # using root level ${SECRET_DOMAIN} breaks flux-local
          - apps.${SECRET_DOMAIN}
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: 80
        annotations:
          hajimari.io/enable: 'false'
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
