---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8tz
  namespace: system-controllers # Required for Renovate lookups
spec:
  interval: 30m
  url: https://k8tz.github.io/k8tz/
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8tz
spec:
  interval: 1h
  chart:
    spec:
      chart: k8tz
      version: 0.17.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: k8tz
        namespace: system-controllers
  values:
    namespace: system-controllers

    replicaCount: 2

    timezone: ${TIMEZONE}
    cronJobTimeZone: true

    webhook:
      certManager:
        enabled: true
        issuerRef:
          name: k8tz-webhook-selfsign
          kind: Issuer

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: k8tz
              topologyKey: kubernetes.io/hostname

  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Namespace
            patch: |-
              $patch: delete
              apiVersion: v1
              kind: Namespace
              metadata:
                name: not-used
