---
# yaml-language-server: $schema=https://raw.githubusercontent.com/kashalls/kromgo/main/config.schema.json
badge:
  font: Verdana.ttf
  size: 12

metrics:
  - name: talos_version
    query: label_replace(node_os_info{name="Talos"}, "version_id", "$1", "version_id", "v(.+)")
    label: version_id
    title: Talos

  - name: kubernetes_version
    query: label_replace(kubernetes_build_info{service="kubernetes"}, "git_version", "$1", "git_version", "v(.+)")
    label: git_version
    title: Kubernetes

  - name: flux_version
    query: label_replace(flux_instance_info, "revision", "$1", "revision", "v(.+)@sha256:.+")
    label: revision
    title: Flux

  - name: cluster_node_count
    query: count(count by (node) (kube_node_status_condition{condition="Ready"}))
    colors:
      - { color: 'green', min: 0, max: 9999 }
    title: Nodes

  - name: cluster_pod_count
    query: sum(kube_pod_status_phase{phase="Running"})
    colors:
      - { color: 'green', min: 0, max: 9999 }
    title: Pods

  - name: cluster_cpu_usage
    query: round(avg(instance:node_cpu_utilisation:rate5m{kubernetes_node!=""}) * 100, 0.1)
    title: CPU
    suffix: '%'
    colors:
      - { color: 'green', min: 0, max: 35 }
      - { color: 'orange', min: 36, max: 75 }
      - { color: 'red', min: 76, max: 9999 }

  - name: cluster_memory_usage
    query: round(sum(node_memory_MemTotal_bytes{kubernetes_node!=""} - node_memory_MemAvailable_bytes{kubernetes_node!=""}) / sum(node_memory_MemTotal_bytes{kubernetes_node!=""}) * 100, 0.1)
    title: Memory
    suffix: '%'
    colors:
      - { color: green, min: 0, max: 35 }
      - { color: orange, min: 36, max: 75 }
      - { color: red, min: 76, max: 9999 }

  - name: cluster_power_usage
    # nut_power_watts is always 0 on this UPS...
    # this doesn't at all match what is shown on the LCD (about half, unless it's only battery power, then it matches)
    # and it also doesn't match what a smart plug shows (which is in between the two values)
    # I'm assuming it's because of how it's trying to calculate the wattage @ 12volts for the battery vs wattage @ 120v for the wall power or something
    # either way, divide by 1.4 or subtracting 400 seems about right to make the numbers at least somewhat correct according to a smart plug
    # which results in nut_power_nominal_watts * nut_load / 1.4
    # or we can just directly use the smart plug, if we pull it from HA
    query: round(ha_sensor_power_w{entity="sensor.cluster_outlet_current_consumption"}, 0.1)
    title: Power
    suffix: 'w'
    colors:
      - { color: 'green', min: 0, max: 400 }
      - { color: 'orange', min: 401, max: 750 }
      - { color: 'red', min: 751, max: 9999 }

  - name: cluster_age_days
    query: round((time() - min(kube_node_created) ) / 86400)
    title: Age
    suffix: 'd'
    colors:
      - { color: 'green', min: 0, max: 180 }
      - { color: 'orange', min: 181, max: 360 }
      - { color: 'red', min: 361, max: 9999 }

  - name: cluster_uptime_days
    query: round(avg(node_time_seconds{kubernetes_node!=""} - node_boot_time_seconds{kubernetes_node!=""}) / 86400)
    suffix: 'd'
    colors:
      - { color: 'green', min: 0, max: 180 }
      - { color: 'orange', min: 181, max: 360 }
      - { color: 'red', min: 361, max: 9999 }

  - name: cluster_alert_count
    query: alertmanager_alerts{state="active"} - 1 # Ignore Watchdog
    colors:
      - { color: 'green', min: 0, max: 0 }
      - { color: 'red', min: 1, max: 9999 }
    title: Alerts
