# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:MLx0HuGhiMiyYQw0MvK7sSDuHfLP1IQWNzEGpwV7fQc1VMRgzsA3Pw==,iv:EYM+lvZhwrDfTnVzaW3YfW5iFxgCEkdf07Q1gdPsc7o=,tag:X1Ryl7rfNNxYpmxHhSbxLQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1j34t6fwv5evlf9gxchc3x9v6zypufszzuynxycrxk4r4jwxtfq9ss9dmtr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TzRWUVNleXRRY2h3aDhF
        MGROUVRNbmJkTWZ6a1pCY1lxRHBscjNDazBZCk5ZNmduYkF0ajlZQllaN3ZZUWJI
        MTVMSWRQZGhYY1lLZjFTVVExTkNvelkKLS0tIG5YdmRWV2NVajBhWEpycjJGL0Vr
        RG5QSDFyb2tzNVhmY0tLbW5XV3hWZ1EK80pHakheHXVy2NPr6bIEq82hg1hW6oXi
        uq7tbzy/r8IKpt3MiUQqKFT1oWzkDoIeIvlHifMEorw+QKcx1dApnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T02:00:04Z"
  mac: ENC[AES256_GCM,data:7dLM+A9VBf0MwN7ezAdP0CTcP4z0R6q5/bFMnuBu9ciDz3+OG+YiZExwAnof6AN9Zk8VBjjfeeYbbAXyIGVn4BArjWsX4GjOJ/uXhlqh31gb8weA/8DKkb1asVyTigNKTBsAJ1UE3jA1zE47hkOJFacPg8uW0ehl/m5tIE19K8k=,iv:kJVKUqx2pheebRVWE4sVlaYUoGBle/cV2xLhArpXDzg=,tag:dqqPxpygshxGl6WW7Xf04Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
