---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: healthcheck-io-gatus-ep
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: healthcheck-io-gatus-ep
    template:
      metadata:
        labels:
          gatus.io/enabled: 'true'
      data:
        config.yaml: |
          endpoints:
          - name: "healthchecks.io"
            group: infrastructure
            url: "{{ .HEALTHCHECK_IO_HEARTBEAT }}"
            interval: 1m
            method: POST
            ui:
              hide-url: true
              hide-hostname: true
            conditions:
              - "[STATUS] == 200"
  dataFrom:
    - extract:
        key: gatus
