kind: Kustomization
resources:
  - externalsecret.yaml
  - ingress.yaml
  - pvc.yaml
  - service.yaml
  - statefulset.yaml
images:
  - name: linuxserver/unifi-controller
    newTag: 9.0.108-ls76
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: default
labels:
  - includeSelectors: true
    pairs:
      app: unifi-controller
      app.kubernetes.io/instance: unifi-controller
      app.kubernetes.io/name: unifi-controller
