---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: actions-runner-controller-secret
    template:
      data:
        github_app_id: '{{ .GITHUB_APP_ID }}'
        github_app_installation_id: '{{ .GITHUB_APP_INSTALLATION_ID }}'
        github_app_private_key: '{{ .GITHUB_APP_PRIVATE_KEY }}'
  dataFrom:
    - extract:
        key: github
