---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: silence-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: silence-operator
      version: 0.0.7
      sourceRef:
        kind: HelmRepository
        name: wiremind
        namespace: observability
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: silence-operator-crds
      namespace: observability
  values:
    image:
      name: quay.io/giantswarm/silence-operator
    operator:
      config:
        alertmanager:
          service:
            address: http://kube-prometheus-stack-alertmanager:9093
    rbac:
      create: true
    extraDeploy:
      - apiVersion: monitoring.giantswarm.io/v1alpha1
        kind: Silence
        metadata:
          name: ceph-node-nfsmount-diskspace-warning
          namespace: observability
        spec:
          matchers:
            - name: alertname
              value: CephNodeDiskspaceWarning
              isRegex: false
            - name: mountpoint
              value: (/etc/nfsmount.conf|/var)
              isRegex: true
      - apiVersion: monitoring.giantswarm.io/v1alpha1
        kind: Silence
        metadata:
          # there are separate btrfs warnings setup, since the defaults aren't accurate for btrfs
          name: no-regular-filesystem-out-of-space-warning-on-btrfs
          namespace: observability
        spec:
          matchers:
            - name: alertname
              value: (NodeFilesystemAlmostOutOfSpace|NodeFilesystemSpaceFillingUp)
              isRegex: true
            - name: job
              value: node-exporter
              isRegex: false
            - name: fstype
              value: btrfs
              isRegex: false
