---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: loki
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 6.28.0
  url: oci://ghcr.io/onedr0p/charts-mirror/loki
  verify:
    provider: cosign
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: loki
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      analytics:
        reporting_enabled: false
      server:
        log_level: info
      commonConfig:
        replication_factor: 1
      compactor:
        working_directory: /var/loki/compactor/retention
        delete_request_store: filesystem
        retention_enabled: true
      ingester:
        chunk_encoding: snappy
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: '2024-04-01' # quote
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      querier:
        # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
        max_concurrent: 4
      pattern_ingester:
        enabled: true
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
        retention_period: 14d
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: ceph-block
        size: 50Gi
      resources:
        requests:
          cpu: 100m
          memory: 768Mi
        limits:
          memory: 2Gi
    gateway:
      replicas: 0
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    lokiCanary:
      enabled: false
    test:
      enabled: false
    sidecar:
      image:
        repository: ghcr.io/kiwigrid/k8s-sidecar
      rules:
        searchNamespace: ALL
    monitoring:
      serviceMonitor:
        enabled: true
