---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    # in GitRepository or ImageUpdateAutomation, reference this as `.spec.secretRef.name`
    name: github-auth
    template:
      data:
        app-id: '{{ .GITHUB_APP_ID }}'
        app-installation-id: '{{ .GITHUB_APP_INSTALLATION_ID }}'
        app-private-key: '{{ .GITHUB_APP_PRIVATE_KEY }}'
  dataFrom:
    - extract:
        key: github
