---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: emqx
  namespace: emqx # Required for renovate lookups
spec:
  interval: 12h
  url: https://repos.emqx.io/charts
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emqx
spec:
  interval: 1h
  chart:
    spec:
      chart: emqx-operator
      version: 2.2.28
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: emqx
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    fullnameOverride: emqx
    replicaCount: 1
    image:
      repository: ghcr.io/emqx/emqx-operator
