# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:csPyZIvBIm4XRmdP,iv:nOcfGYYVTbChw/fkwhyfmE6Ia/tpQEhU+xuWZOLu83Q=,tag:x3wR7ERTka7c9j6sZvH4TA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:5jZMFRl7c0oGRAE3VJXdErVJlzp9LiqHn6jP05KJnhs2n7Pr,iv:ADSzuOhhEz1qybPzkZauOTEuzbQRrfjjbe+XU4kH6S0=,tag:TCpCkaO65RdUTXVspFmsJw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1j34t6fwv5evlf9gxchc3x9v6zypufszzuynxycrxk4r4jwxtfq9ss9dmtr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaElDdFhlSFIxS2gxOVd1
        NUVMbzhaUkxMQnNaSTI0NlhkRWhJaGdLbkJ3CmFsQmY1ZzdYK0xrdkRXUmxGTTRn
        WU05aWl6MHhjY2VTQjZ5TkZha1JFU2MKLS0tIFVHR29Lc1FLTHdONFRWcHJHN3Vh
        MnhpZ1MzeTVoS243WjBUb092YVBZVUEKC3mam4zj6S/YVAlWHTPFTOnD6Bk5DcR7
        L/KSBjoLCG7eaIDjIJw6FoY0CJ5y7VWxJfFcf/OsTL2LXtpUdQm1vA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T02:00:04Z"
  mac: ENC[AES256_GCM,data:HXt52L/JOzHcQxQAdQ1PfSzzqqMzK/3lpJiaqTJzNTETzs38AqQQRwcRwNfeqejvr5gzv3mH3iCuB96lTXPnjIkYbFSF6AYtZsUUd4z2EDtwBHL9hEILicPA4hX+XEfbwq6x3LJoReHmDfKmZy0Ty45jCQ9HsIfE3o/VAO4BJTI=,iv:vK9i5NJ9arwrt7fFMBqg3kvXtON0CFsxWYq/kKgHWq0=,tag:zfiG5cvYTXss2EckyTZmCg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
