---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./mutations # this HAS to be first for the mutation to take effect before the statefulset gets created!
  - ./unifi-mongo.yaml
