endpoints:
  - name: '${APP}'
    group: guarded
    url: 'https://${GATUS_SUBDOMAIN:=${APP}}.${SECRET_DOMAIN}${GATUS_PATH:=/}'
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    conditions:
      - '[STATUS] == ${GATUS_STATUS:=200}'
    alerts:
      - type: pushover
