endpoints:
  - name: '${APP}'
    group: guarded
    url: 1.1.1.1
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    dns:
      query-name: '${GATUS_SUBDOMAIN:=${APP}}.${SECRET_DOMAIN}'
      query-type: A
    conditions:
      - 'len([BODY]) == 0'
  - name: '${APP}'
    group: internal
    url: 'https://${GATUS_SUBDOMAIN:=${APP}}.${SECRET_DOMAIN}${GATUS_PATH:=/}'
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    conditions:
      - '[STATUS] == ${GATUS_STATUS:=200}'
