apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:62efGBBsb6SW4PidfrwW6TP4wH8qDnES5Tlqao69fKYL179C3e4lNn/TNW3s9J9hkDO9/w2m/+WdiM21v4htA0LW7oS4WPIcr6k=,iv:2I8HOTX7A/jFodbMjyeqNFrOdmTttKSQ3uNAfyy6jH8=,tag:bcWsC3WDS9LFTIDa61xPWQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1j34t6fwv5evlf9gxchc3x9v6zypufszzuynxycrxk4r4jwxtfq9ss9dmtr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQXRYeUErOW42ZjVYbHRv
        cGRueW1XWWpwY0VmK0NYblBZZjBCUnhhMUFVCm8yYW9DTENETDBOdk9XMHIwUkJk
        RjRXMHhzWjdadnlVR0xSbU8zYytnc1EKLS0tIE53N1plYkgxamVvSm1KQlZKRVBR
        UkljNXR2QnBIUzRjOGphdEQ3Uk9naDQK2GA3GJ0OJJeAgxJqCJTx0Jtt5AnVEb4J
        Xfm5ipgZ2Pdi0h8vPu9jY1FZdGQCHQQdPq1IzDCwPRfcNwtgurC85Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T02:27:04Z"
  mac: ENC[AES256_GCM,data:1G+49qrFG4/RpX7iqQeLq0X/ZnRluEnJofKrsJ9P5X9tcBvI9q13v44Y86IJP9VRuHdgZRD3Mu8Zl92NqnHuytbcxyt96dUscOrxBG/gqFVcp1KcD20PP5Txw7AoCHLhw5CFO0cD6UOUBlbcwdve/EgOgw2YJuzNMBCm/ef0Oco=,iv:wezVeAHlzlRnGOAm0wVV9LuKh94TJ8zWVhFpiR1YX9c=,tag:96ksErQOlHHs02oKP/I2Bg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
