---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: emqx
resources:
  - ./emqx/ks.yaml
components:
  - ../../components/common
