---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: grafana-admin-secret
    template:
      data:
        API_USER: '{{ .API_USER }}'
        API_PASSWORD: '{{ .API_PASSWORD }}'
  dataFrom:
    - extract:
        key: nut
