---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nut
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: nut-secret
    template:
      data:
        API_PASSWORD: '{{ .NUT_API_PASSWORD }}'

  dataFrom:
    - extract:
        key: nut
