---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nut
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: RollingUpdate
        pod:
          nodeSelector:
            # can't use node-feature-discovery, because the ups just disconnects/connects forever, until nut connects to it
            kubernetes.io/hostname: nas
        containers:
          upsd:
            image:
              repository: docker.io/instantlinux/nut-upsd
              tag: latest@sha256:98d54b54e0bae4167312bcaec8c22de925f9ab9594da4f15b1102c5762372fc7
            securityContext:
              readOnlyRootFilesystem: true
              privileged: true
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 256Mi
            env:
              DRIVER: 'usbhid-ups'
              DESCRIPTION: 'Main Cluster UPS'
            envFrom:
              - secretRef:
                  name: nut-upsd-secret
          exporter:
            image:
              repository: docker.io/hon95/prometheus-nut-exporter
              tag: '1.2.1'
            env:
              HTTP_PATH: &metrics /metrics
              RUST_LOG: debug
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
                custom: false
              startup:
                enabled: true
                custom: false
            resources:
              requests:
                cpu: 15m
                memory: 30Mi
              limits:
                memory: 50Mi
    service:
      app:
        controller: main
        ports:
          metrics:
            port: 9995
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
            scheme: http
            path: *metrics
            scrapeTimeout: 10s
            params:
              target: ['localhost:3493']
            relabelings:
              - sourceLabels: [__param_target]
                targetLabel: target
