---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nut
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          nut:
            image:
              repository: docker.io/instantlinux/nut-upsd
              tag: 2.8.2-r2
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 256Mi
                squat.ai/ups-tripp-lite: 1
            env:
              DRIVER: 'usbhid-ups'
              DESCRIPTION: 'Main Cluster UPS'
            envFrom:
              - secretRef:
                  name: nut-secret
          exporter:
            image:
              repository: docker.io/hon95/prometheus-nut-exporter
              tag: '1.2.1'
            env:
              HTTP_PATH: &metrics /metrics
              RUST_LOG: debug
            resources:
              requests:
                cpu: 15m
                memory: 30Mi
              limits:
                memory: 50Mi
        pod:
          nodeSelector:
            ups.feature.node.kubernetes.io/tripp-lite: 'true'
    service:
      main:
        controller: main
        ports:
          http:
            port: 3493
          metrics:
            port: 9995
    serviceMonitor:
      app:
        serviceName: nut
        endpoints:
          - port: metrics
            scheme: http
            path: *metrics
            scrapeTimeout: 10s
            params:
              targets: ['localhost:3493']
            relabelings:
              - sourceLabels: [__param_target]
                targetLabel: target
