---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname esphome
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  path: './kubernetes/apps/default/esphome/app'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: bitwarden-store
      namespace: external-secrets
    - name: volsync
      namespace: volsync-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CAPACITY: 5Gi
