---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2025.3.2@sha256:bc6ac31069eae42f4ff41d2dd0d600aaf8f02b109664cd6aff46709d13eff779
            env:
              HASS_HTTP_TRUSTED_PROXY_1: 192.168.20.0/24
              HASS_HTTP_TRUSTED_PROXY_2: 10.69.0.0/16
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            args:
              - --log-file
              - /config/logs/home-assistant.log
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ['ALL'] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.98.0@sha256:49190032f1ab73cdcd0c930b1e961c20110aa1b6004d296c14681eb11c9f49d8
            args:
              [
                '--auth',
                'none',
                '--user-data-dir',
                '/config/.vscode',
                '--extensions-dir',
                '/config/.vscode',
                '--port',
                '12321',
                '/config',
              ]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: &http 8123
          code-server:
            port: &code 12321
    route:
      app:
        hostnames:
          - ha.${SECRET_DOMAIN}
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *http
        annotations:
          hajimari.io/appName: Home Assistant
          hajimari.io/icon: simple-icons:homeassistant

      code-server:
        hostnames:
          - ha-code.${SECRET_DOMAIN}
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *code
        annotations:
          hajimari.io/appName: Home Assistant Code Server
          hajimari.io/icon: mdi:microsoft-visual-studio-code
    serviceMonitor:
      app:
        serviceName: home-assistant
        endpoints:
          - port: http
            scheme: http
            path: /api/prometheus
            interval: 1m
            scrapeTimeout: 10s
            authorization:
              credentials:
                name: home-assistant-auth-secret
                key: HASS_LONG_LIVED_TOKEN
    persistence:
      config:
        existingClaim: home-assistant
        globalMounts:
          - path: /config
      config-cache:
        existingClaim: home-assistant-cache
        globalMounts:
          - path: /config/.venv
      config-logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      config-tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
