---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbtools
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: qbittorrent
      namespace: default
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: 'OnRootMismatch'
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

    controllers:
      prune:
        type: cronjob

        cronjob: &cronJobSpec
          schedule: '@hourly'
          backoffLimit: 0
          concurrencyPolicy: Forbid
          failedJobsHistory: 1
          successfulJobsHistory: 0

        pod:
          restartPolicy: Never

        initContainers:
          tagging: &container
            image:
              repository: ghcr.io/buroa/qbtools
              tag: v0.19.14
            args:
              - tagging
              - --added-on
              - --expired
              - --last-activity
              - --sites
              - --unregistered
              - --server
              - &qbittorrent_host qbittorrent.default.svc.cluster.local
              - --port
              - &qbittorrent_port '80'
              - --config
              - /config/config.yaml
            envFrom:
              - secretRef:
                  name: qbtools-secret
            resources:
              requests:
                memory: 128Mi
                cpu: 25m
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

        containers:
          expired:
            <<: *container
            args:
              - prune
              - --exclude-category
              - manual
              - --exclude-category
              - cross-seed
              - --exclude-tag
              - added:24h
              - --include-tag
              - expired
              - --server
              - *qbittorrent_host
              - --port
              - *qbittorrent_port
              - --dry-run

          unregistered:
            <<: *container
            args:
              - prune
              - --exclude-category
              - manual
              - --exclude-category
              - cross-seed
              - --exclude-tag
              - added:24h
              - --include-tag
              - unregistered
              - --server
              - *qbittorrent_host
              - --port
              - *qbittorrent_port
              - --dry-run

      orphaned:
        type: cronjob
        cronjob:
          <<: *cronJobSpec
          schedule: '@daily'
        pod:
          restartPolicy: Never
        containers:
          app:
            <<: *container
            args:
              - orphaned
              - --exclude-pattern
              - '*/manual/*'
              - --exclude-pattern
              - '*/cross-seed/*'
              - --server
              - *qbittorrent_host
              - --port
              - *qbittorrent_port
              - --dry-run

      reannounce:
        containers:
          app:
            <<: *container
            args:
              - reannounce
              - --process-seeding
              - --server
              - *qbittorrent_host
              - --port
              - *qbittorrent_port

    persistence:
      config-file:
        type: secret
        name: qbtools-config-secret
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
      media:
        type: nfs
        server: nfs.servers.internal
        path: /media
        advancedMounts:
          orphaned:
            app:
              - path: /media/downloads/qbittorrent
                subPath: downloads/qbittorrent
