---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: rook-ceph
      version: v1.16.5
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: snapshot-controller
      namespace: volsync-system
  values:
    csi:
      cephFSKernelMountOptions: ms_mode=prefer-crc
      enableLiveness: true
      serviceMonitor:
        enabled: true
      csiRBDPluginResource: |
        - name : driver-registrar
          resource:
            requests:
              memory: 16Mi # 128Mi is default
              cpu: 50m # default
            limits:
              memory: 256Mi # default
        - name : csi-rbdplugin
          resource:
            requests:
              memory: 128Mi # 512Mi is default
              cpu: 250m # default
            limits:
              memory: 1Gi # Default
        - name : liveness-prometheus
          resource:
            requests:
              memory: 64Mi # 128Mi is default
              cpu: 50m # default
            limits:
              memory: 256Mi # default
      csiCephFSPluginResource: |
        - name : driver-registrar
          resource:
            requests:
              memory: 16Mi # 128Mi is default
              cpu: 50m # default
            limits:
              memory: 256Mi # default
        - name : csi-cephfsplugin
          resource:
            requests:
              memory: 128Mi # 512Mi is default
              cpu: 250m # default
            limits:
              memory: 1Gi # default
        - name : liveness-prometheus
          resource:
            requests:
              memory: 64Mi # 128Mi is default
              cpu: 50m # default
            limits:
              memory: 256Mi # default
    enableDiscoveryDaemon: true
    image:
      repository: ghcr.io/rook/ceph
    monitoring:
      enabled: true
    resources:
      requests:
        memory: 128Mi # unchangable
        cpu: 100m # unchangable
      limits: {}
