---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: rook-ceph
      version: v1.16.3
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  # dependsOn:
  #   - name: snapshot-controller
  #     namespace: volsync-system
  values:
    csi:
      cephFSKernelMountOptions: ms_mode=prefer-crc
      enableLiveness: true
      serviceMonitor:
        enabled: true
      csiRBDPluginResource: |
        - name : driver-registrar
          resource:
            requests:
              memory: 16Mi
              cpu: 50m
            limits:
              memory: 256Mi
        - name : csi-rbdplugin
          resource:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 1Gi
        - name : liveness-prometheus
          resource:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 256Mi
      csiCephFSPluginResource: |
        - name : driver-registrar
          resource:
            requests:
              memory: 16Mi
              cpu: 50m
            limits:
              memory: 256Mi
        - name : csi-cephfsplugin
          resource:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 1Gi
        - name : liveness-prometheus
          resource:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 256Mi
        enableDiscoveryDaemon: true
    monitoring:
      enabled: true
    resources:
      requests:
        memory: 128Mi # unchangable
        cpu: 100m # unchangable
      limits: {}
