---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
configMapGenerator:
  - name: pihole-configmap
    files:
      - update.sh=./configs/update.sh
      - dnscrypt-proxy.toml=./configs/dnscrypt-proxy.toml
      - 02-custom.conf=./configs/02-custom.conf
      - 03-hosts.conf=./configs/03-hosts.conf
generatorOptions:
  disableNameSuffixHash: true
